# Use official Python base image
FROM python:3.13-slim

# Actualizamos los repositorios e instalamos las dependencias del sistema necesarias
RUN apt-get update && apt-get install -y libpq-dev gcc

# Set the working directory inside the container
WORKDIR /booking_service

# Copy the requirements file into the container
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the microservice code into the container
COPY . .

# Expose the port your Django app will run on
EXPOSE 8001

# Start the Django development server
#CMD ["python", "manage.py", "runserver", "0.0.0.0:8001"]
