# Use a stable Python base image
FROM python:3.12-slim

# Actualizamos los repositorios e instalamos las dependencias del sistema necesarias
RUN apt-get update && apt-get install -y libpq-dev gcc

# Set the working directory inside the container
WORKDIR /user_service

# Copy the requirements file into the container
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your code into the container
COPY . .

# Expose port (optional: depending on how you run the service)
EXPOSE 8006

# Start Django server (you may customize this later for Gunicorn/Uvicorn)
CMD ["python", "src/manage.py", "runserver", "0.0.0.0:8006"]
#CMD ["tail", "-f", "/dev/null"] You do this when you don't have a django project yet 